############################################################
# +------------------------------------------------------+ #
# |                Glowstone Development                 | #
# +------------------------------------------------------+ #
############################################################

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when Server-Bot loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)
#   - Text with symbols is enclosed in single or double quotation marks
#
# We recommend you use a text editor like Sublime Text or Atom Text Editor (Both windows and mac compatible) or Notepad++(Windows only) to edit this document
# https://www.sublimetext.com/3      https://atom.io/     https://notepad-plus-plus.org/downloads/




# Paste your discord bot token in-between the double quotes (Make sure you've watched the video on)
discord_bot_token: "your bot token here"


# Create a role called "Factions bot" or "Developer" and paste it's id here.
# The point is those with the role will have full access to the bot commands.
developer_role_id: '842714308576018453'


# Minecraft alt's username (email)
username: 'your mc username'


# Minecraft alt's password
password: 'your mc pass'


# Authentication Server
# If your alt is a mojang account, leave it as it is.
# If your alt is a Microsoft account, replace "mojang" with "microsoft"
auth: 'mojang'


# Embed color, Only hex codes https://htmlcolorcodes.com/color-picker/
embed_color: "#E200FF"



############################################################
# +------------------------------------------------------+ #
# |                     Application                      | #
# +------------------------------------------------------+ #
############################################################


application_settings:
  questions: 
    - "What is your IGN?"
    - "What is your age?"
    - "What is your timezone?"
    - "How often can you play? How many hours can you play in a day? And are you willing to put in the hours/grind?"
    - "What are your pfs and do you have anyone who can vouch for you?"
    - "Are you able to perform voice calls?"
    - "Do you have any knowledge with cannoning or patching?"
    - "Explain how to patch against a non ap cannon"
    - "Explain how to patch against a ap cannon"
    - "Explain what is buffer-check and how you do it"
    - "Why do you want to join Cunts? And why should we accept you?"
  accepted_response: "Hey your application was reviewed by the management, and we would like to inform you that your application has been accepted.\nPlease message a Co-leader to get started with your interview."
  rejected_response: "Hey your application was reviewed by the management, and we are sorry to inform you that your application has been rejected."
